version: '2'
services:
  plugin:
    image: buildkite/plugin-tester:latest@sha256:58a345bc2dbafed28c2deb5096dc8cb6c4a11958da9d890c02f5a3d870eef836
    volumes:
      - ".:/plugin"
    depends_on:
      - ruby
  ruby:
    image: ruby:2.6-alpine@sha256:164ad2564d946833890177b9fdc440701e18bd5bf1e32f27fcc9c04131dd1a9c
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"